=== ghimiresiddhartha/Siddhartha-Music-Store/catalog_19031691.dtd
<!ELEMENT schema (Store)>
<!ELEMENT Store (Store_Info, Songs)> 
<!ELEMENT Store_Info (Store_Name, Logo, Address+, Phone+, Website+)>
<!ELEMENT Store_Name (#PCDATA)>
<!ELEMENT Logo EMPTY>
<!ELEMENT Address (Country, City)>
<!ELEMENT Country (#PCDATA)>
<!ELEMENT City (#PCDATA)>
<!ELEMENT Phone (Landline, Mobile)>
<!ELEMENT Landline (#PCDATA)>
<!ELEMENT Mobile (#PCDATA)>
<!ELEMENT Website (URL)>
<!ELEMENT URL ANY>
<!ELEMENT Songs (Categories+)>
<!ELEMENT Categories (genre+)>
<!ELEMENT genre (Name, (pic1|pic2|pic3|pic4|pic5|pic6|pic7|pic8|pic9|pic10|pic11|pic12|pic13|pic14|pic15)?, singer, song_description+, Quantity*, Price, additional_info+)>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT pic1 EMPTY>
<!ELEMENT pic2 EMPTY>
<!ELEMENT pic3 EMPTY>
<!ELEMENT pic4 EMPTY>
<!ELEMENT pic5 EMPTY>
<!ELEMENT pic6 EMPTY>
<!ELEMENT pic7 EMPTY>
<!ELEMENT pic8 EMPTY>
<!ELEMENT pic9 EMPTY>
<!ELEMENT pic10 EMPTY>
<!ELEMENT pic11 EMPTY>
<!ELEMENT pic12 EMPTY>
<!ELEMENT pic13 EMPTY>
<!ELEMENT pic14 EMPTY>
<!ELEMENT pic15 EMPTY>
<!ELEMENT singer (#PCDATA)>
<!ELEMENT song_description (#PCDATA|b)*>
<!ELEMENT b (#PCDATA)>
<!ELEMENT Quantity (#PCDATA|b)*>
<!ELEMENT Price (#PCDATA|b)*>
<!ELEMENT additional_info (category+, Released+, Recorded*, Writer+, Producer+)>
<!ELEMENT category (#PCDATA|b)*>
<!ELEMENT Released (#PCDATA|b)*>
<!ELEMENT Recorded (#PCDATA|b)*>
<!ELEMENT Writer (#PCDATA|b)*>
<!ELEMENT Producer (#PCDATA|b)*>


<!ATTLIST schema xmlns:xsi CDATA #FIXED "http://www.w3.org/2001/XMLSchema-instance">
<!ATTLIST schema xsi:noNamespaceSchemaLocation CDATA #FIXED "catalog_19031691.xsd">
<!ATTLIST genre Type NMTOKENS #REQUIRED>
<!ATTLIST Store_Info type CDATA #FIXED "about">
<!ATTLIST singer artist CDATA #REQUIRED>
<!ATTLIST singer id ID #REQUIRED>
<!ATTLIST singer artist IDREF #IMPLIED>
<!ATTLIST additional_info location NMTOKEN #REQUIRED>

=== ghimiresiddhartha/Siddhartha-Music-Store/Development/catalog_19031691.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="catalog_19031691.css"?> <!--CSS Refrence-->
<!DOCTYPE schema SYSTEM "catalog_19031691.dtd"> <!-- DTD Refrence-->
<schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="catalog_19031691.xsd"><!-- Schema Refrence-->
	<!--
   		Author: Siddhartha Ghimire
   		Date:   May 5, 2021
	-->
	
	<Store> <!--Main Section-->
		<Store_Info type="about"> <!--Contains Store Information-->
			<Store_Name>Siddhartha Music Store</Store_Name>
			<Logo></Logo>
			<Address>
				<Country>Nepal</Country>
				<City>Lalitpur</City>
			</Address>
			<Phone>
				<Landline>Landline:(01) 236745</Landline>
				<Mobile>Mobile:(977) 9800818055</Mobile>
			</Phone>
			<Website>
				<URL><![CDATA[www.siddharthamusicstore.com.np]]></URL> <!-- CDATA stores every type of characters-->
			</Website>
		</Store_Info>
		<!--End of Store Information-->

		<Songs> <!--Sub Main Section-->
			<Categories> <!--Jazzs music Container-->
				<genre Type="Jazzs Jazz-1"> <!--type1-->
					<Name>Take Five</Name>
					<pic1></pic1>
					<singer id="a1" artist="DBQ">Singer: Dave Brubeck Quartet</singer>
					<song_description>
						<b>Description:</b>
						<![CDATA["Take Five" is known for its distinctive two-chord piano/bass vamp;infectious, cool-jazz saxophone melodies; innovative, jolting drum solo;and unconventional quintuple time, which Dave Brubeck derived its name from.]]>
					</song_description>
					<Quantity><b>Available:</b> 2</Quantity>
					<Price><b>Price:</b> &#163;20 per album</Price>
					<additional_info location="Jazz-1">
						<category><b>Genre:</b>Jazz</category>
						<Released><b>Released Date:</b> May 22, 1961</Released>
						<Recorded><b>Recorded Date:</b> July 1, 1959</Recorded>
						<Writer><b>Song Writer:</b> Paul Desmond</Writer>
						<Producer><b>Song Producer:</b> Teo Macero</Producer>
					</additional_info>
				</genre><!--End of type1-->
				<genre Type="Jazzs Jazz-2"> <!--type2-->
					<Name>So What</Name>
					<pic2></pic2>
					<singer id="a2" artist="MD">Singer: Miles Davis</singer>
					<song_description>
						<b>Description:</b> 
						<![CDATA["So What" is the most well-known examples of modal jazz, written in the Dorian mode and consisting of 16 bars of D Dorian, eight bars of E Dorian, and eight more of D Dorian. This AABA arrangement conforms to the thirty-two-bar style of popular songs in the United States.]]>
					</song_description>
					<Price><b>Price:</b> &#163;19 per album - Out of Stock</Price>
					<additional_info location="Jazz-2">
						<category><b>Genre:</b> Modal Jazz</category>
						<Released><b>Released Date:</b> August 17, 1959</Released>
						<Recorded><b>Recorded Date:</b> March 2, 1959</Recorded>
						<Writer><b>Song Writer:</b> Miles Davis</Writer>
						<Producer><b>Song Producer:</b> Teo Macero</Producer>
					</additional_info>
				</genre><!--End of type2-->
				<genre Type="Jazzs Jazz-3"> <!--type3-->
					<Name>Round Midnight</Name>
					<pic3></pic3>
					<singer id="a3" artist="TM">Singer: Thelonious Monk</singer>
					<song_description>
						<b>Description:</b> 
						<![CDATA["Round Midnight" is a 1944 composition by pianist Thelonious Monk that soon became a jazz standard and has been covered by a diverse range of artists. In 1993, a version recorded by Monk's quintet was inducted into the Grammy Hall of Fame. It is one of the most often played jazz standards written by a jazz musician.]]>
					</song_description>
					<Quantity>
						<b>Available:</b> 3
					</Quantity>
					<Price><b>Price:</b> &#163;21 per album</Price>
					<additional_info location="Jazz-3">
						<category><b>Genre:</b> Jazz</category>
						<Released><b>Released Date:</b> 1959</Released>
						<Recorded><b>Recorded Date:</b>1993</Recorded>
						<Writer><b>Song Writer:</b> Thelonious Monk</Writer>
						<Producer><b>Song Producer:</b> Thelonious Monk</Producer>
					</additional_info>
				</genre><!--End of type3-->
				<genre Type="Jazzs Jazz-4"> <!--type4-->
					<Name>A Love Supreme</Name>
					<pic4></pic4>
					<singer id="a4" artist="JC">Singer: John Coltrane</singer>
					<song_description>
						<b>Description:</b> 
						<![CDATA["A Love Supreme (Acknowledgment)" is one of the greatest songs of all time, as well as one of John Coltrane's best-selling and most critically praised. It is widely regarded as his magnum opus. On the first track, "Acknowledgement," the album starts with the bang of a gong (tam-tam) and cymbal washes.]]>
					</song_description>
					<Quantity><b>Available:</b> 3</Quantity>
					<Price><b>Price:</b> &#163;22 per album</Price>
					<additional_info location="Jazz-4">
						<category><b>Genre:</b> Modal Jazz</category>
						<Released><b>Released Date:</b> January 1965</Released>
						<Recorded><b>Recorded Date:</b> December 9, 1964</Recorded>
						<Writer><b>Song Writer:</b> John Coltrane</Writer>
						<Producer><b>Song Producer:</b> Bob Thiele</Producer>
					</additional_info>
				</genre><!--End of type4-->
				<genre Type="Jazzs Jazz-5"> <!--type5-->
					<Name>All Blues</Name>
					<pic5></pic5>
					<singer id="a5" artist="MD" >Singer: Miles Davis</singer>
					<song_description>
						<b>Description:</b> 
						<![CDATA["All Blues" is a Miles Davis jazz arrangement that first appeared on the influential 1959 album Kind of Blue. Furthermore, there is a harmonically close vamp played by the horns at the start and then (usually) continued by the piano under any solos that occur. Each chorus is usually divided by a four-bar vamp that serves as an introduction to the following solo/chorus.]]>
					</song_description>
					<Quantity><b>Available:</b> 2</Quantity>
					<Price><b>Price:</b> &#163;20 per album</Price>
					<additional_info location="Jazz-5">
						<category><b>Genre:</b> Modal Jazz</category>
						<Released><b>Released Date:</b> August 17, 1959</Released>
						<Recorded><b>Recorded Date:</b> April 22, 1959</Recorded>
						<Writer><b>Song Writer:</b> Miles Davis</Writer>
						<Producer><b>Song Producer:</b> Irving Townsend</Producer>
					</additional_info>
				</genre><!--End of type5-->
				<genre Type="Jazzs Jazz-6"><!--type6-->
					<Name>Strange Fruit</Name>
					<pic6></pic6>
					<singer id="a6" artist="BH">Singer: Billie Holiday</singer>
					<song_description>
						<b>Description:</b> 
						<![CDATA["Strange Fruit" is a protest song against lynchings of African-Americans, with lyrics comparing the victims to tree fruit. At the turn of the twentieth century, such lynchings had reached a high in the Southern United States, with the vast majority of victims being black. The song has been described as "a manifesto" and "the start of the civil rights movement.]]>
					</song_description>
					<Price><b>Price:</b> &#163;20 per album - Out of Stock</Price>
					<additional_info location="Jazz-6">
						<category><b>Genre:</b> Blues, Jazz</category>
						<Released><b>Released Date:</b> 1939</Released>
						<Recorded><b>Recorded Date:</b> April 10, 1939</Recorded>
						<Writer><b>Song Writer:</b> Abel Meeropol</Writer>
						<Producer><b>Song Producer:</b> Milt Gabler</Producer>
					</additional_info>
				</genre><!--End of type6-->
			</Categories> <!--End of Container-->
			<Categories> <!--Rocks music Container-->
				<genre Type="Rocks Rock-1"><!--type1-->
					<Name>Purple Haze</Name>
					<pic7></pic7>
					<singer id="a7" artist="JHE">Singer: Jimi Hendrix Experience</singer>
					<song_description>
						<b>Description:</b> 
						<![CDATA[Jimi's innovative guitar playing is included in this music, which utilizes the signature Hendrix chord and a blend of blues and Eastern modalities influenced by novel sound processing techniques. Due to ambiguity in the lyrics, listeners sometimes read the song as relating to a trance encounter, despite Hendrix's description of it as a love song.]]>
					</song_description>
					<Quantity><b>Available:</b> 2</Quantity>
					<Price><b>Price:</b> &#163;30 per album</Price>
					<additional_info location="Rock-1">
						<category><b>Genre:</b> Hard Rock</category>
						<Released><b>Released Date:</b> March 17, 1967</Released>
						<Recorded><b>Recorded Date:</b> January 11, 1967</Recorded>
						<Writer><b>Song Writer:</b> Jimi Hendrix</Writer>
						<Producer><b>Song Producer:</b> Chas Chandler</Producer>
					</additional_info>
				</genre><!--End of type1-->
				<genre Type="Rocks Rock-2"> <!--type2-->
					<Name>Start Me Up</Name>
					<pic8></pic8>
					<singer id="a8" artist="TRS">Singer: The Rolling Stones</singer>
					<song_description>
						<b>Description:</b> 
						<![CDATA[The Rolling Stones' "Start Me Up" is a single from their 1981 album Tattoo You. It debuted at number one on the Australian Kent Music Report, number two in Canada, number two on the Billboard Hot 100, number seven on the UK Singles Chart, and number ten in a few European countries north of the Alps.]]>
					</song_description>
					<Quantity><b>Available:</b> 3</Quantity>
					<Price><b>Price:</b> &#163;35 per album</Price>
					<additional_info location="Rock-2">
						<category><b>Genre:</b> Hard Rock</category>
						<Released><b>Released Date:</b> August 14, 1981</Released>
						<Recorded><b>Recorded Date:</b> January and March 1978</Recorded>
						<Writer><b>Song Writer:</b> Jagger/Richards</Writer>
						<Producer><b>Song Producer:</b> The Glimmer Twins</Producer>
					</additional_info>
				</genre><!--End of type2-->
				<genre Type="Rocks Rock-3"><!--type3-->
					<Name>Whole Lotta Love</Name>
					<pic9></pic9>
					<singer id="a9" artist="LZ">Singer: Led Zeppelin</singer>
					<song_description>
						<b>Description:</b>
